version: '3'
services:
  coupon:
    container_name: coupon
    # restart: always
    build:
      context: ./coupon
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./coupon:/usr/src/app
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    container_name: postgres
    image: postgres:11.2-alpine
    volumes:
      - data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data: