version: '3'
services:
  coupon:
    build:
      context: ./coupon
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./coupon:/usr/src/app
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  data: